### ISSUE TITLE
'Error:  could not find function "dat0"' on dataset InsectSprays 

### ISSUE THREAD

**Issue by AndreaPi** [ryantimpe/rspivot#4]
As per subject, calling

`rspivot:::rspivot(InsectSprays)`

results in an error 

```
valueName: value not found in input dataframe. Please check function call.
 could not find function "dat0"
```

I have installed Shiny: btw, why not including it in the required installs, like `rhandsontable`, instead than having the user install it by itself? Maybe it's not needed?

**Comment by ryantimpe** [comment]
In the function call, you'll need to tell it the name of the column(s) that contain values. Otherwise, it doesn't know if a column is descriptive or a value. Use the valueName parameter.

Also, the function doesn't work for 1-dimensional data frames (never thought it would be needed). But if you put in a dummy dimension, it works.

rspivot::rspivot(InsectSprays %>% mutate(ID = "Sprays"), valueName = "count")

**Comment by AndreaPi** [comment]
Right, sorry - the 1D dataframe example doesn't make a lot of sense, but I actually found the issue with a multidimensional dataframe. I used `InsectSprays` just to have a reproducible example. If you're interested, I can update the issue with a multi-D dataframe, otherwise I'll  just use the `valueName` argument. Just for clarity, I need to pass all value columns as a character vector to `valueName`, and the columns that remain outside can be used for grouping/pivoting, right?
